-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."boosted_ideas" add column "completed_at" timestamp with time zone
--  null;
