fragment UserFields on users {
	displayName
	id
	avatarUrl
	address {
		...UserAddress
	}
}

fragment UserFieldsWithEmail on users {
	...UserFields
	email
}

fragment UserAddress on user_address {
	location
	country
}
