fragment UserFields on users {
	displayName
	id
	avatarUrl
	createdAt
	address {
		...UserAddress
	}
}

fragment UserFieldsWithEmail on users {
	...UserFields
	email
}

fragment UserAddress on user_address {
	location
	country
}

fragment UserSearch on user_profile {
	skills
	startups
	availability
	specialistIndustry
	status
	objective
	pronouns
	customPronouns
	user {
		...UserFields
	}
}
