table:
  name: match_settings
  schema: public
configuration:
  column_config:
    looking_for:
      custom_name: lookingFor
  custom_column_names:
    looking_for: lookingFor
  custom_root_fields: {}
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - looking_for
        - skills
        - type
        - user_id
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - looking_for
        - skills
        - type
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
