table:
  name: match_settings
  schema: public
configuration:
  column_config:
    looking_for:
      custom_name: lookingFor
    user_id:
      custom_name: userId
  custom_column_names:
    looking_for: lookingFor
    user_id: userId
  custom_root_fields: {}
select_permissions:
  - role: user
    permission:
      columns:
        - user_id
        - looking_for
        - type
        - skills
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - looking_for
        - skills
        - type
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
      set:
        user_id: x-hasura-User-Id
