-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."idea_comment_replies" add column "target_user_id" uuid
--  not null;
