-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_esteem_points_currency" add column "currency" money
--  not null default '0';
