-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO notification_types (value, description) VALUES ('PROFILE_NOT_SET', 'Profile not set'), ('COMMENT', 'New comment'), ('REPLY', 'New reply'), ('MESSAGE', 'New message'), ('CURRENCY', 'Earned currency'), ('ESTEEM_POINTS', 'Earned esteem points');
