mutation UpdateMatchSettings(
	$id: uuid!
	$match_settings: match_settings_set_input!
) {
	update_match_settings_by_pk(
		pk_columns: { userId: $id }
		_set: $match_settings
	) {
		lookingFor
		skills
		type
	}
}

query MatchSettings($id: uuid!) {
	settings: match_settings_by_pk(userId: $id) {
		...MatchSettingsFields
	}
}

fragment MatchSettingsFields on match_settings {
	type
	skills
	lookingFor
}

# query Matches($lookingFor: String!, $skills: jsonb!, $currentUserId: uuid!) {
# 	users(
# 		where: {
# 			matchSettings: {
# 				type: { _eq: $lookingFor }
# 				# _and: { user_id: { _neq: $currentUserId } }
# 				_and: {
# 					user_id: { _neq: $currentUserId }
# 					_and: { skills: { _contains: $skills } }
# 				}
# 			}
# 		}
# 		order_by: { lastSeen: desc, matchSettings: { skills: asc } }
# 	) {
# 		displayName
# 		email
# 		id
# 		avatarUrl
# 		profile {
# 			skills
# 		}
# 	}
# }

# query Matches($currentUserId: uuid!, $lookingFor: String!, $skills: jsonb) {
# 	users(
# 		where: {
# 			id: { _neq: $currentUserId }
# 			matchSettings: {
# 				type: { _eq: $lookingFor }
# 				skills: { _has_keys_any: $skills }
# 			}
# 		}
# 	) {
# 		displayName
# 		id
# 		avatarUrl
# 		matchSettings {
# 			type
# 			skills
# 		}
# 	}
# }

query Matches(
	$currentUserId: uuid!
	$userLookingFor: String!
	$userProfileSkills: [String!]
) {
	users(
		where: {
			id: { _neq: $currentUserId }
			matchSettings: { type: { _ilike: $userLookingFor } }
			profile: { skills: { _has_keys_any: $userProfileSkills } }
		}
	) {
		displayName
		id
		avatarUrl
		matchSettings {
			type
		}
		profile {
			skills
		}
	}
}
