query UserSocials($id: uuid!) {
	profile: user_profile_by_pk(id: $id) {
		linkedin
		twitter
		website
	}
}

query User($user_id: uuid!) {
	user: users_by_pk(id: $user_id) {
		id
		last_name
		first_name
		location
		country
		avatar_url
		created_at
		account {
			email
		}
		user_profile {
			id
			is_complete
		}
	}
}

mutation UpdateUserProfile($id: uuid!, $user_profile: user_profile_set_input!) {
	update_user_profile_by_pk(pk_columns: { id: $id }, _set: $user_profile) {
		id
		availability
		background
		linkedin
		twitter
		instagram
		facebook
		resume
		statement
		status
		business_description
		startups
		website
		skills
		is_complete
		specialist_industry
		updated_at
	}
}

query UserExperience($id: uuid!) {
	profile: user_profile_by_pk(id: $id) {
		id
		user_id
		background
		statement
		startups
		status
		availability
		business_description
		specialist_industry
		skills
		resume
		linkedin
		twitter
		instagram
		facebook
		website
		updated_at
		is_complete
	}
}

mutation UpdateUserExperience(
	$id: uuid!
	$userExperience: user_profile_set_input!
) {
	update_user_profile_by_pk(pk_columns: { id: $id }, _set: $userExperience) {
		id
		user_id
		background
		statement
		startups
		status
		skills
		availability
		resume
		business_description
	}
}

mutation UpdateResume($id: uuid!, $resume: user_profile_set_input!) {
	update_user_profile_by_pk(pk_columns: { id: $id }, _set: $resume) {
		id
		resume
	}
}

mutation UpdateUserPersonalDetails(
	$id: uuid!
	$userPersonalDetails: users_set_input!
) {
	user: update_users_by_pk(
		pk_columns: { id: $id }
		_set: $userPersonalDetails
	) {
		first_name
		last_name
		location
		country
		avatar_url
	}
}

mutation UpdateUserAvatar($id: uuid!, $avatarUrl: users_set_input!) {
	user: update_users_by_pk(pk_columns: { id: $id }, _set: $avatarUrl) {
		avatar_url
	}
}
