-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE public.idea_comment_replies (
--     id uuid DEFAULT public.gen_random_uuid() NOT NULL,
--     comment_id uuid NOT NULL,
--     user_id uuid NOT NULL,
--     value text NOT NULL,
--     created_at timestamp with time zone DEFAULT now(),
--     updated_at timestamp with time zone DEFAULT now()
-- );
