name: Build and deploy Coral app to dev.founderpad.com

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches:
            - dev

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15

            - name: Install yarn
              run: npm install -g yarn

            - name: Install project dependencies
              run: |
                  yarn install --frozen-lockfile --ignore-engines
                  echo "Dependencies installed"

            - name: Install Hasura CLI
              run: |
                  curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
                  echo "Hasura CLI installed successfully"

            - name: Apply Hasura Migration to dev
              working-directory: ./nhost
              run: |
                  hasura migrate apply --endpoint ${{ secrets.HASURA_BACKEND_DEVELOPMENT }} --admin-secret ${{ secrets.HASURA_ADMIN_SECRET_DEVELOPMENT }} --skip-update-check
                  echo "Migration applied successfully"

            - name: Apply Hasura Metadata (permissions, object/array relationships, events etc) to dev Postgres
              working-directory: ./nhost
              run: |
                  hasura metadata apply --endpoint ${{ secrets.HASURA_BACKEND_DEVELOPMENT }} --admin-secret ${{ secrets.HASURA_ADMIN_SECRET_DEVELOPMENT }} --skip-update-check
                  echo "Metadata applied successfully"

            - name: Run tests
              run: yarn test

            - name: Run build
              run: yarn build

            - name: Run tests against Vercel
              env:
                  VERCEL_URL: ${{ steps.pilot.outputs.preview-url }}
              run: yarn test

            - name: Deploy to development
              run: npx vercel --token ${VERCEL_TOKEN}
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    notify:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Slack Notification
              run: |
                  POST ${{ secrets.SLACK_NOTIFICATION_DEV_DEPLOYMENT }}
                  Content-type: application/json
                  {
                      "text": "Danny Torrence left a 1 star review for your property.",
                      "blocks": [
                        {
                          "type": "section",
                          "text": {
                            "type": "mrkdwn",
                            "text": "Danny Torrence left the following review for your property:"
                          }
                        },
                        {
                          "type": "section",
                          "block_id": "section567",
                          "text": {
                            "type": "mrkdwn",
                            "text": "<https://example.com|Overlook Hotel> \n :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                          },
                          "accessory": {
                            "type": "image",
                            "image_url": "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg",
                            "alt_text": "Haunted hotel image"
                          }
                        },
                        {
                          "type": "section",
                          "block_id": "section789",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Average Rating*\n1.0"
                            }
                          ]
                        }
                      ]
                  }
