-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- DROP TRIGGER insert_user_match_settings ON users CASCADE;
-- DROP FUNCTION insert_user_matchmake_settings_func() CASCADE;
