-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO comment_status_types (value, description)
-- VALUES
-- ('PENDING', 'The comment is in the pending state'),
-- ('APPROVED', 'The comment is in the approved state'),
-- ('REJECTED', 'The comment is in the rejected state');
